/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class ABoolFactor extends PFactor
{
    private TBooldenotation _booldenotation_;

    public ABoolFactor()
    {
        // Constructor
    }

    public ABoolFactor(
        @SuppressWarnings("hiding") TBooldenotation _booldenotation_)
    {
        // Constructor
        setBooldenotation(_booldenotation_);

    }

    @Override
    public Object clone()
    {
        return new ABoolFactor(
            cloneNode(this._booldenotation_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABoolFactor(this);
    }

    public TBooldenotation getBooldenotation()
    {
        return this._booldenotation_;
    }

    public void setBooldenotation(TBooldenotation node)
    {
        if(this._booldenotation_ != null)
        {
            this._booldenotation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._booldenotation_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._booldenotation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._booldenotation_ == child)
        {
            this._booldenotation_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._booldenotation_ == oldChild)
        {
            setBooldenotation((TBooldenotation) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
