/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class ADefProg extends PProg
{
    private PDef _def_;
    private PProg _prog_;

    public ADefProg()
    {
        // Constructor
    }

    public ADefProg(
        @SuppressWarnings("hiding") PDef _def_,
        @SuppressWarnings("hiding") PProg _prog_)
    {
        // Constructor
        setDef(_def_);

        setProg(_prog_);

    }

    @Override
    public Object clone()
    {
        return new ADefProg(
            cloneNode(this._def_),
            cloneNode(this._prog_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADefProg(this);
    }

    public PDef getDef()
    {
        return this._def_;
    }

    public void setDef(PDef node)
    {
        if(this._def_ != null)
        {
            this._def_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._def_ = node;
    }

    public PProg getProg()
    {
        return this._prog_;
    }

    public void setProg(PProg node)
    {
        if(this._prog_ != null)
        {
            this._prog_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prog_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._def_)
            + toString(this._prog_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._def_ == child)
        {
            this._def_ = null;
            return;
        }

        if(this._prog_ == child)
        {
            this._prog_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._def_ == oldChild)
        {
            setDef((PDef) newChild);
            return;
        }

        if(this._prog_ == oldChild)
        {
            setProg((PProg) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
