/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class AGreqRelop extends PRelop
{
    private TGreqsym _greqsym_;

    public AGreqRelop()
    {
        // Constructor
    }

    public AGreqRelop(
        @SuppressWarnings("hiding") TGreqsym _greqsym_)
    {
        // Constructor
        setGreqsym(_greqsym_);

    }

    @Override
    public Object clone()
    {
        return new AGreqRelop(
            cloneNode(this._greqsym_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGreqRelop(this);
    }

    public TGreqsym getGreqsym()
    {
        return this._greqsym_;
    }

    public void setGreqsym(TGreqsym node)
    {
        if(this._greqsym_ != null)
        {
            this._greqsym_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._greqsym_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._greqsym_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._greqsym_ == child)
        {
            this._greqsym_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._greqsym_ == oldChild)
        {
            setGreqsym((TGreqsym) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
