/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class ALseqRelop extends PRelop
{
    private TLseqsym _lseqsym_;

    public ALseqRelop()
    {
        // Constructor
    }

    public ALseqRelop(
        @SuppressWarnings("hiding") TLseqsym _lseqsym_)
    {
        // Constructor
        setLseqsym(_lseqsym_);

    }

    @Override
    public Object clone()
    {
        return new ALseqRelop(
            cloneNode(this._lseqsym_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALseqRelop(this);
    }

    public TLseqsym getLseqsym()
    {
        return this._lseqsym_;
    }

    public void setLseqsym(TLseqsym node)
    {
        if(this._lseqsym_ != null)
        {
            this._lseqsym_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lseqsym_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lseqsym_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lseqsym_ == child)
        {
            this._lseqsym_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lseqsym_ == oldChild)
        {
            setLseqsym((TLseqsym) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
