/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class AMinusAddop extends PAddop
{
    private TMinussym _minussym_;

    public AMinusAddop()
    {
        // Constructor
    }

    public AMinusAddop(
        @SuppressWarnings("hiding") TMinussym _minussym_)
    {
        // Constructor
        setMinussym(_minussym_);

    }

    @Override
    public Object clone()
    {
        return new AMinusAddop(
            cloneNode(this._minussym_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMinusAddop(this);
    }

    public TMinussym getMinussym()
    {
        return this._minussym_;
    }

    public void setMinussym(TMinussym node)
    {
        if(this._minussym_ != null)
        {
            this._minussym_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minussym_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minussym_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minussym_ == child)
        {
            this._minussym_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minussym_ == oldChild)
        {
            setMinussym((TMinussym) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
