/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class AMulTerm extends PTerm
{
    private PTerm _term_;
    private PMulop _mulop_;
    private PAddopfactor _addopfactor_;

    public AMulTerm()
    {
        // Constructor
    }

    public AMulTerm(
        @SuppressWarnings("hiding") PTerm _term_,
        @SuppressWarnings("hiding") PMulop _mulop_,
        @SuppressWarnings("hiding") PAddopfactor _addopfactor_)
    {
        // Constructor
        setTerm(_term_);

        setMulop(_mulop_);

        setAddopfactor(_addopfactor_);

    }

    @Override
    public Object clone()
    {
        return new AMulTerm(
            cloneNode(this._term_),
            cloneNode(this._mulop_),
            cloneNode(this._addopfactor_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMulTerm(this);
    }

    public PTerm getTerm()
    {
        return this._term_;
    }

    public void setTerm(PTerm node)
    {
        if(this._term_ != null)
        {
            this._term_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._term_ = node;
    }

    public PMulop getMulop()
    {
        return this._mulop_;
    }

    public void setMulop(PMulop node)
    {
        if(this._mulop_ != null)
        {
            this._mulop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mulop_ = node;
    }

    public PAddopfactor getAddopfactor()
    {
        return this._addopfactor_;
    }

    public void setAddopfactor(PAddopfactor node)
    {
        if(this._addopfactor_ != null)
        {
            this._addopfactor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._addopfactor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._term_)
            + toString(this._mulop_)
            + toString(this._addopfactor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._term_ == child)
        {
            this._term_ = null;
            return;
        }

        if(this._mulop_ == child)
        {
            this._mulop_ = null;
            return;
        }

        if(this._addopfactor_ == child)
        {
            this._addopfactor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._term_ == oldChild)
        {
            setTerm((PTerm) newChild);
            return;
        }

        if(this._mulop_ == oldChild)
        {
            setMulop((PMulop) newChild);
            return;
        }

        if(this._addopfactor_ == oldChild)
        {
            setAddopfactor((PAddopfactor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
