/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class ANoteqRelop extends PRelop
{
    private TNoteqsym _noteqsym_;

    public ANoteqRelop()
    {
        // Constructor
    }

    public ANoteqRelop(
        @SuppressWarnings("hiding") TNoteqsym _noteqsym_)
    {
        // Constructor
        setNoteqsym(_noteqsym_);

    }

    @Override
    public Object clone()
    {
        return new ANoteqRelop(
            cloneNode(this._noteqsym_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANoteqRelop(this);
    }

    public TNoteqsym getNoteqsym()
    {
        return this._noteqsym_;
    }

    public void setNoteqsym(TNoteqsym node)
    {
        if(this._noteqsym_ != null)
        {
            this._noteqsym_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._noteqsym_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._noteqsym_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._noteqsym_ == child)
        {
            this._noteqsym_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._noteqsym_ == oldChild)
        {
            setNoteqsym((TNoteqsym) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
