/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class APlusAddop extends PAddop
{
    private TPlussym _plussym_;

    public APlusAddop()
    {
        // Constructor
    }

    public APlusAddop(
        @SuppressWarnings("hiding") TPlussym _plussym_)
    {
        // Constructor
        setPlussym(_plussym_);

    }

    @Override
    public Object clone()
    {
        return new APlusAddop(
            cloneNode(this._plussym_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlusAddop(this);
    }

    public TPlussym getPlussym()
    {
        return this._plussym_;
    }

    public void setPlussym(TPlussym node)
    {
        if(this._plussym_ != null)
        {
            this._plussym_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plussym_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._plussym_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._plussym_ == child)
        {
            this._plussym_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._plussym_ == oldChild)
        {
            setPlussym((TPlussym) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
