/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleExpr extends PExpr
{
    private PSmplexpr _smplexpr_;

    public ASimpleExpr()
    {
        // Constructor
    }

    public ASimpleExpr(
        @SuppressWarnings("hiding") PSmplexpr _smplexpr_)
    {
        // Constructor
        setSmplexpr(_smplexpr_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleExpr(
            cloneNode(this._smplexpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleExpr(this);
    }

    public PSmplexpr getSmplexpr()
    {
        return this._smplexpr_;
    }

    public void setSmplexpr(PSmplexpr node)
    {
        if(this._smplexpr_ != null)
        {
            this._smplexpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._smplexpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._smplexpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._smplexpr_ == child)
        {
            this._smplexpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._smplexpr_ == oldChild)
        {
            setSmplexpr((PSmplexpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
