/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class ATimesMulop extends PMulop
{
    private TTimessym _timessym_;

    public ATimesMulop()
    {
        // Constructor
    }

    public ATimesMulop(
        @SuppressWarnings("hiding") TTimessym _timessym_)
    {
        // Constructor
        setTimessym(_timessym_);

    }

    @Override
    public Object clone()
    {
        return new ATimesMulop(
            cloneNode(this._timessym_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATimesMulop(this);
    }

    public TTimessym getTimessym()
    {
        return this._timessym_;
    }

    public void setTimessym(TTimessym node)
    {
        if(this._timessym_ != null)
        {
            this._timessym_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._timessym_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._timessym_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._timessym_ == child)
        {
            this._timessym_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._timessym_ == oldChild)
        {
            setTimessym((TTimessym) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
