/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class TIdivsym extends Token
{
    public TIdivsym()
    {
        super.setText("\\");
    }

    public TIdivsym(int line, int pos)
    {
        super.setText("\\");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TIdivsym(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIdivsym(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TIdivsym text.");
    }
}
