/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class TThensym extends Token
{
    public TThensym()
    {
        super.setText("THEN");
    }

    public TThensym(int line, int pos)
    {
        super.setText("THEN");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TThensym(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTThensym(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TThensym text.");
    }
}
